name: Incoming PullRequest
on: [pull_request]
jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - name: prettier
        run: |
          npx prettier -c --config=.prettierrc ./projects/cosmos-ui/src/**/*.{html,scss,ts}

      - name: commitlint
        run: |
          FIRST_COMMIT_SHA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.pull_request.commits_url }} | jq -r '.[0].sha')
          npm ci
          npx commitlint --from $FIRST_COMMIT_SHA^

      - name: tslint
        run: |
          npx tslint --project projects/cosmos-ui/tsconfig.lib.prod.json

      - name: test
        run: |
          npx ng test --watch=false --browsers=ChromeHeadlessCustom
